worlds:
  hub: hub
  lobby: lobby
  maps:
    sample:
      spawn:
        x: 0
        y: 57
        z: 0
        rot: 90
      blue:
        spawn:
          x: -34
          y: 65
          z: -23
          rot: -90
        flag:
          x: -53
          y: 65
          z: 18
          rot: 12
      red:
        spawn:
          x: 34
          y: 65
          z: 23
          rot: 90
        flag:
          x: 53
          y: 65
          z: -18
          rot: 4